export interface Form {
    addChangeDeleteFlag: null,
    btnCndAdd: null,
    btnCndCopy: null,
    btnCndDelete: null,
    btnCndModify: null,
    btnCndRenumber: null,
    btnCndView: null,
    btnCndViewDetail: null,
    btnLblAdd: null,
    btnLblCopy: null,
    btnLblDelete: null,
    btnLblModify: null,
    btnLblRenumber: null,
    btnLblView: null,
    btnLblViewDetail: null,
    btnResAdd: null,
    btnResCopy: null,
    btnResDelete: null,
    btnResModify: null,
    btnResRenumber: null,
    btnResView: null,
    btnResViewDetail: null,
    comment: null,
    condition: null,
    helpText: null,
    hidden: null,
    hidePremium: null,
    formType:null,
    scriptBefore:null,
    scriptAfter:null,
    maxOccurs: null,
    minOccurs: null,
    name: null,
    number: null,
    ratebookId: '00000000-0000-0000-0000-000000000000',
    sequence: null,
    subSequence: null,
    tabCondition: null,
    tabResourceName: null,
    tableId: null,
    templateFile: null,
    type: null,
    id:'00000000-0000-0000-0000-000000000000'
}
